name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        cd website
        npm ci

    - name: Build Docusaurus site
      run: |
        cd website
        npm run build

    - name: Copy build files to /docs folder
      run: |
        rm -rf docs
        mkdir docs
        cp -R website/build/* docs/

    - name: Check for changes in /docs folder
      id: changes
      run: |
        git add docs
        git diff --cached --exit-code || echo "has_changes=true" >> $GITHUB_ENV

    - name: Commit and push changes
      if: env.has_changes == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git commit -m "Update GitHub Pages site"
        git push
